server:
  port: 8001
spring:
  application:
    name: test
dandelion:
  route:
    id: aaa
    url: http://localhost:8001
    predicates:
      - Path=adada,dadada
      - hello=adadada
    filters:
      - StripPrefix=1
